name: calendar_resource
description: A package calendar making by Vido Team
version: 1.0.0

homepage: https://github.com/vuitv/calendar_resource
repository: https://github.com/vuitv/calendar_resource.git
issue_tracker: https://github.com/vuitv/calendar_resource/issues
documentation: https://github.com/vuitv/calendar_resource

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: 8.0.3
  equatable: 2.0.3

  flutter:
    sdk: flutter

  flutter_bloc: 8.0.1
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
